[package]
name = "aedron_patchouli-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }
autobins = false

[lib]
path = "src/main.rs"
crate-type = ["cdylib"]

[dependencies]
console_log = "^1.0.0"
log = { workspace = true }
wasm-bindgen = "^0.2.87"
[dependencies.kobold]
version = "^0.9.1"
features = ["rlsf"]