BEGIN EXCLUSIVE TRANSACTION;

CREATE TABLE IF NOT EXISTS plugins (
	name TEXT NOT NULL,
	kind TEXT NOT NULL,
	version TEXT NOT NULL,

	PRIMARY KEY (name, kind) ON CONFLICT REPLACE
) STRICT;

COMMIT TRANSACTION;
